# Calculate Basic Statistics of Detailed Reviews

In [2]:
import gzip
import json
import re
import os
import sys
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:,}'.format

**Specify your directory here:**

In [3]:
DIR = './'
DIR_GENRE = './genre/'

**Calculate statistics of book reviews (without spoiler tags)**

In [4]:
def count_reviews(file_name):
    print('counting file:', file_name)
    n_review = 0
    book_set, user_set = set(), set()
    print('current line: ', end='')
    with gzip.open(file_name) as fin:
        for l in fin:
            d = json.loads(l)
            if n_review % 1000000 == 0:
                print(n_review, end=',')
            n_review += 1
            book_set.add(d['book_id'])
            user_set.add(d['user_id'])
    print('complete')
    print('done!')
    return n_review, len(book_set), len(user_set)

In [14]:
DIR = './'
DIR_GENRE = './genre/'
file_name = os.path.join(DIR, 'goodreads_reviews_dedup.json.gz')
n_review = 0
with gzip.open(file_name) as fin:
        for l in fin:
            d = json.loads(l)
            if n_review > 0:
                break
            print(d.keys())
            print(d['review_text'])
            n_review += 1

dict_keys(['user_id', 'book_id', 'review_id', 'rating', 'review_text', 'date_added', 'date_updated', 'read_at', 'started_at', 'n_votes', 'n_comments'])
Mind blowingly cool. Best science fiction I've read in some time. I just loved all the descriptions of the society of the future - how they lived in trees, the notion of owning property or even getting married was gone. How every surface was a screen.
 The undulations of how society responds to the Trisolaran threat seem surprising to me. Maybe its more the Chinese perspective, but I wouldn't have thought the ETO would exist in book 1, and I wouldn't have thought people would get so over-confident in our primitive fleet's chances given you have to think that with superior science they would have weapons - and defenses - that would just be as rifles to arrows once were.
 But the moment when Luo Ji won as a wallfacer was just too cool. I may have actually done a fist pump. Though by the way, if the Dark Forest theory is right - and I see no reason why it wouldn't be - we as a society should probably stop broadcasting so much signal out into the universe.

In [1]:
print('Hello world')

Hello world

In [2]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import torch

#warnings.filterwarnings('ignore')
model = AutoModelForSequenceClassification.from_pretrained("KevSun/Personality_LM", ignore_mismatched_sizes=True)
tokenizer = AutoTokenizer.from_pretrained("KevSun/Personality_LM")

# Choose between direct text input or file input
use_file = False  # Set to True if you want to read from a file

#if use_file:
#    file_path = 'path/to/your/textfile.txt'  # Replace with your file path
#    with open(file_path, 'r', encoding='utf-8') as file:
#        new_text = file.read()
#else:
new_text = "President Joe Biden said on Wednesday he pulled out of the race against Republican Donald Trump over concerns about the future of U.S. democracy, explaining he was stepping aside to allow a new generation to take over in his first public remarks since ending his re-election bid. In an Oval Office address, Biden invoked previous presidents Thomas Jefferson, George Washington, and Abraham Lincoln as he described his love for the office that he will leave in six months, capping a half century in public office."

# Encode the text using the same tokenizer used during training
encoded_input = tokenizer(new_text, return_tensors='pt', padding=True, truncation=True, max_length=64)

model.eval()  # Set the model to evaluation mode

# Perform the prediction
with torch.no_grad():
    outputs = model(**encoded_input)


predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
predicted_scores = predictions[0].tolist()


trait_names = ["agreeableness", "openness", "conscientiousness", "extraversion", "neuroticism"]


for trait, score in zip(trait_names, predicted_scores):
    print(f"{trait}: {score:.4f}")

##"output":
#agreeableness: 0.2138
#openness: 0.2890
#conscientiousness: 0.1921
#extraversion: 0.1307
#neuroticism: 0.1744

config.json:   0%|          | 0.00/995 [00:00<?, ?B/s]

C:\Users\ryanr\miniconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ryanr\.cache\huggingface\hub\models--KevSun--Personality_LM. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of the model checkpoint at KevSun/Personality_LM were not used when initializing RobertaForSequenceClassification: ['hidden_layer.bias', 'hidden_layer.weight', 'output_layer.bias', 'output_layer.weight', 'transformer.embeddings.LayerNorm.bias', 'transformer.embeddings.LayerNorm.weight', 'transformer.embeddings.position_embeddings.weight', 'transformer.embeddings.token_type_embeddings.weight', 'transformer.embeddings.word_embeddings.weight', 'transformer.encoder.layer.0.attention.output.LayerNorm.bias', 'transformer.encoder.layer.0.attention.output.LayerNorm.weight', 'transformer.encoder.layer.0.attention.output.dense.bias', 'transformer.encoder.layer.0.attention.output.dense.weight', 'transformer.encoder.layer.0.attention.self.key.bias', 'transformer.encoder.layer.0.attention.self.key.weight', 'transformer.encoder.layer.0.attention.self.query.bias', 'transformer.encoder.layer.0.attention.self.query.weight', 'transformer.encoder.layer.0.attention.self.value.bias', 'transformer.encoder.layer.0.attention.self.value.weight', 'transformer.encoder.layer.0.intermediate.dense.bias', 'transformer.encoder.layer.0.intermediate.dense.weight', 'transformer.encoder.layer.0.output.LayerNorm.bias', 'transformer.encoder.layer.0.output.LayerNorm.weight', 'transformer.encoder.layer.0.output.dense.bias', 'transformer.encoder.layer.0.output.dense.weight', 'transformer.encoder.layer.1.attention.output.LayerNorm.bias', 'transformer.encoder.layer.1.attention.output.LayerNorm.weight', 'transformer.encoder.layer.1.attention.output.dense.bias', 'transformer.encoder.layer.1.attention.output.dense.weight', 'transformer.encoder.layer.1.attention.self.key.bias', 'transformer.encoder.layer.1.attention.self.key.weight', 'transformer.encoder.layer.1.attention.self.query.bias', 'transformer.encoder.layer.1.attention.self.query.weight', 'transformer.encoder.layer.1.attention.self.value.bias', 'transformer.encoder.layer.1.attention.self.value.weight', 'transformer.encoder.layer.1.intermediate.dense.bias', 'transformer.encoder.layer.1.intermediate.dense.weight', 'transformer.encoder.layer.1.output.LayerNorm.bias', 'transformer.encoder.layer.1.output.LayerNorm.weight', 'transformer.encoder.layer.1.output.dense.bias', 'transformer.encoder.layer.1.output.dense.weight', 'transformer.encoder.layer.10.attention.output.LayerNorm.bias', 'transformer.encoder.layer.10.attention.output.LayerNorm.weight', 'transformer.encoder.layer.10.attention.output.dense.bias', 'transformer.encoder.layer.10.attention.output.dense.weight', 'transformer.encoder.layer.10.attention.self.key.bias', 'transformer.encoder.layer.10.attention.self.key.weight', 'transformer.encoder.layer.10.attention.self.query.bias', 'transformer.encoder.layer.10.attention.self.query.weight', 'transformer.encoder.layer.10.attention.self.value.bias', 'transformer.encoder.layer.10.attention.self.value.weight', 'transformer.encoder.layer.10.intermediate.dense.bias', 'transformer.encoder.layer.10.intermediate.dense.weight', 'transformer.encoder.layer.10.output.LayerNorm.bias', 'transformer.encoder.layer.10.output.LayerNorm.weight', 'transformer.encoder.layer.10.output.dense.bias', 'transformer.encoder.layer.10.output.dense.weight', 'transformer.encoder.layer.11.attention.output.LayerNorm.bias', 'transformer.encoder.layer.11.attention.output.LayerNorm.weight', 'transformer.encoder.layer.11.attention.output.dense.bias', 'transformer.encoder.layer.11.attention.output.dense.weight', 'transformer.encoder.layer.11.attention.self.key.bias', 'transformer.encoder.layer.11.attention.self.key.weight', 'transformer.encoder.layer.11.attention.self.query.bias', 'transformer.encoder.layer.11.attention.self.query.weight', 'transformer.encoder.layer.11.attention.self.value.bias', 'transformer.encoder.layer.11.attention.self.value.weight', 'transformer.encoder.layer.11.intermediate.dense.bias', 'transformer.encoder.layer.11.intermediate.dense.weight', 'transformer.encoder.layer.11.output.LayerNorm.bias', 'transformer.encoder.layer.11.output.LayerNorm.weight', 'transformer.encoder.layer.11.output.dense.bias', 'transformer.encoder.layer.11.output.dense.weight', 'transformer.encoder.layer.2.attention.output.LayerNorm.bias', 'transformer.encoder.layer.2.attention.output.LayerNorm.weight', 'transformer.encoder.layer.2.attention.output.dense.bias', 'transformer.encoder.layer.2.attention.output.dense.weight', 'transformer.encoder.layer.2.attention.self.key.bias', 'transformer.encoder.layer.2.attention.self.key.weight', 'transformer.encoder.layer.2.attention.self.query.bias', 'transformer.encoder.layer.2.attention.self.query.weight', 'transformer.encoder.layer.2.attention.self.value.bias', 'transformer.encoder.layer.2.attention.self.value.weight', 'transformer.encoder.layer.2.intermediate.dense.bias', 'transformer.encoder.layer.2.intermediate.dense.weight', 'transformer.encoder.layer.2.output.LayerNorm.bias', 'transformer.encoder.layer.2.output.LayerNorm.weight', 'transformer.encoder.layer.2.output.dense.bias', 'transformer.encoder.layer.2.output.dense.weight', 'transformer.encoder.layer.3.attention.output.LayerNorm.bias', 'transformer.encoder.layer.3.attention.output.LayerNorm.weight', 'transformer.encoder.layer.3.attention.output.dense.bias', 'transformer.encoder.layer.3.attention.output.dense.weight', 'transformer.encoder.layer.3.attention.self.key.bias', 'transformer.encoder.layer.3.attention.self.key.weight', 'transformer.encoder.layer.3.attention.self.query.bias', 'transformer.encoder.layer.3.attention.self.query.weight', 'transformer.encoder.layer.3.attention.self.value.bias', 'transformer.encoder.layer.3.attention.self.value.weight', 'transformer.encoder.layer.3.intermediate.dense.bias', 'transformer.encoder.layer.3.intermediate.dense.weight', 'transformer.encoder.layer.3.output.LayerNorm.bias', 'transformer.encoder.layer.3.output.LayerNorm.weight', 'transformer.encoder.layer.3.output.dense.bias', 'transformer.encoder.layer.3.output.dense.weight', 'transformer.encoder.layer.4.attention.output.LayerNorm.bias', 'transformer.encoder.layer.4.attention.output.LayerNorm.weight', 'transformer.encoder.layer.4.attention.output.dense.bias', 'transformer.encoder.layer.4.attention.output.dense.weight', 'transformer.encoder.layer.4.attention.self.key.bias', 'transformer.encoder.layer.4.attention.self.key.weight', 'transformer.encoder.layer.4.attention.self.query.bias', 'transformer.encoder.layer.4.attention.self.query.weight', 'transformer.encoder.layer.4.attention.self.value.bias', 'transformer.encoder.layer.4.attention.self.value.weight', 'transformer.encoder.layer.4.intermediate.dense.bias', 'transformer.encoder.layer.4.intermediate.dense.weight', 'transformer.encoder.layer.4.output.LayerNorm.bias', 'transformer.encoder.layer.4.output.LayerNorm.weight', 'transformer.encoder.layer.4.output.dense.bias', 'transformer.encoder.layer.4.output.dense.weight', 'transformer.encoder.layer.5.attention.output.LayerNorm.bias', 'transformer.encoder.layer.5.attention.output.LayerNorm.weight', 'transformer.encoder.layer.5.attention.output.dense.bias', 'transformer.encoder.layer.5.attention.output.dense.weight', 'transformer.encoder.layer.5.attention.self.key.bias', 'transformer.encoder.layer.5.attention.self.key.weight', 'transformer.encoder.layer.5.attention.self.query.bias', 'transformer.encoder.layer.5.attention.self.query.weight', 'transformer.encoder.layer.5.attention.self.value.bias', 'transformer.encoder.layer.5.attention.self.value.weight', 'transformer.encoder.layer.5.intermediate.dense.bias', 'transformer.encoder.layer.5.intermediate.dense.weight', 'transformer.encoder.layer.5.output.LayerNorm.bias', 'transformer.encoder.layer.5.output.LayerNorm.weight', 'transformer.encoder.layer.5.output.dense.bias', 'transformer.encoder.layer.5.output.dense.weight', 'transformer.encoder.layer.6.attention.output.LayerNorm.bias', 'transformer.encoder.layer.6.attention.output.LayerNorm.weight', 'transformer.encoder.layer.6.attention.output.dense.bias', 'transformer.encoder.layer.6.attention.output.dense.weight', 'transformer.encoder.layer.6.attention.self.key.bias', 'transformer.encoder.layer.6.attention.self.key.weight', 'transformer.encoder.layer.6.attention.self.query.bias', 'transformer.encoder.layer.6.attention.self.query.weight', 'transformer.encoder.layer.6.attention.self.value.bias', 'transformer.encoder.layer.6.attention.self.value.weight', 'transformer.encoder.layer.6.intermediate.dense.bias', 'transformer.encoder.layer.6.intermediate.dense.weight', 'transformer.encoder.layer.6.output.LayerNorm.bias', 'transformer.encoder.layer.6.output.LayerNorm.weight', 'transformer.encoder.layer.6.output.dense.bias', 'transformer.encoder.layer.6.output.dense.weight', 'transformer.encoder.layer.7.attention.output.LayerNorm.bias', 'transformer.encoder.layer.7.attention.output.LayerNorm.weight', 'transformer.encoder.layer.7.attention.output.dense.bias', 'transformer.encoder.layer.7.attention.output.dense.weight', 'transformer.encoder.layer.7.attention.self.key.bias', 'transformer.encoder.layer.7.attention.self.key.weight', 'transformer.encoder.layer.7.attention.self.query.bias', 'transformer.encoder.layer.7.attention.self.query.weight', 'transformer.encoder.layer.7.attention.self.value.bias', 'transformer.encoder.layer.7.attention.self.value.weight', 'transformer.encoder.layer.7.intermediate.dense.bias', 'transformer.encoder.layer.7.intermediate.dense.weight', 'transformer.encoder.layer.7.output.LayerNorm.bias', 'transformer.encoder.layer.7.output.LayerNorm.weight', 'transformer.encoder.layer.7.output.dense.bias', 'transformer.encoder.layer.7.output.dense.weight', 'transformer.encoder.layer.8.attention.output.LayerNorm.bias', 'transformer.encoder.layer.8.attention.output.LayerNorm.weight', 'transformer.encoder.layer.8.attention.output.dense.bias', 'transformer.encoder.layer.8.attention.output.dense.weight', 'transformer.encoder.layer.8.attention.self.key.bias', 'transformer.encoder.layer.8.attention.self.key.weight', 'transformer.encoder.layer.8.attention.self.query.bias', 'transformer.encoder.layer.8.attention.self.query.weight', 'transformer.encoder.layer.8.attention.self.value.bias', 'transformer.encoder.layer.8.attention.self.value.weight', 'transformer.encoder.layer.8.intermediate.dense.bias', 'transformer.encoder.layer.8.intermediate.dense.weight', 'transformer.encoder.layer.8.output.LayerNorm.bias', 'transformer.encoder.layer.8.output.LayerNorm.weight', 'transformer.encoder.layer.8.output.dense.bias', 'transformer.encoder.layer.8.output.dense.weight', 'transformer.encoder.layer.9.attention.output.LayerNorm.bias', 'transformer.encoder.layer.9.attention.output.LayerNorm.weight', 'transformer.encoder.layer.9.attention.output.dense.bias', 'transformer.encoder.layer.9.attention.output.dense.weight', 'transformer.encoder.layer.9.attention.self.key.bias', 'transformer.encoder.layer.9.attention.self.key.weight', 'transformer.encoder.layer.9.attention.self.query.bias', 'transformer.encoder.layer.9.attention.self.query.weight', 'transformer.encoder.layer.9.attention.self.value.bias', 'transformer.encoder.layer.9.attention.self.value.weight', 'transformer.encoder.layer.9.intermediate.dense.bias', 'transformer.encoder.layer.9.intermediate.dense.weight', 'transformer.encoder.layer.9.output.LayerNorm.bias', 'transformer.encoder.layer.9.output.LayerNorm.weight', 'transformer.encoder.layer.9.output.dense.bias', 'transformer.encoder.layer.9.output.dense.weight', 'transformer.pooler.dense.bias', 'transformer.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

agreeableness: 0.1665
openness: 0.1085
conscientiousness: 0.2774
extraversion: 0.1880
neuroticism: 0.2597

In [8]:
def personality_breakdown(new_text):
    encoded_input = tokenizer(new_text, return_tensors='pt', padding=True, truncation=True, max_length=64)

    model.eval()  # Set the model to evaluation mode
    
    # Perform the prediction
    with torch.no_grad():
        outputs = model(**encoded_input)
    
    
    predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
    predicted_scores = predictions[0].tolist()
    
    
    trait_names = ["agreeableness", "openness", "conscientiousness", "extraversion", "neuroticism"]
    
    output = zip(trait_names, predicted_scores)
    for trait, score in zip(trait_names, predicted_scores):
        print(f"{trait}: {score:.4f}")
    return output

In [15]:
print('Breakdown 1')
text = ''''Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.

Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.

But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth.'''
personality_breakdown(text)
text2 = '''I am extroverted'''
print('Breakdown 2')
personality_breakdown(text2)

Breakdown 1
agreeableness: 0.1626
openness: 0.1110
conscientiousness: 0.2716
extraversion: 0.1932
neuroticism: 0.2616
Breakdown 2
agreeableness: 0.1692
openness: 0.1152
conscientiousness: 0.2652
extraversion: 0.1920
neuroticism: 0.2585

In [6]:
n_review, n_book, n_user = count_reviews(os.path.join(DIR, 'goodreads_reviews_dedup.json.gz'))
df_stats_review = pd.DataFrame([n_review, n_book, n_user], dtype=float,
                               columns=['count'], index=['# review', '# book', '# user'])
display(df_stats_review)

counting file: ./goodreads_reviews_dedup.json.gz
current line: 0,1000000,2000000,3000000,4000000,5000000,6000000,7000000,8000000,9000000,10000000,11000000,12000000,13000000,14000000,15000000,complete
done!

                count
# review 15,739,967.0
# book    2,080,190.0
# user      465,323.0

**Calculate statistics of the review subset with spoiler tags**

In [5]:
def count_spoilers(file_name):
    print('counting file:', file_name)
    n_review, n_sentence, n_spoiler_review, n_spoiler_sentence = 0, 0, 0, 0
    book_set, user_set = set(), set()
    print('current line: ', end='')
    with gzip.open(file_name) as fin:
        for l in fin:
            d = json.loads(l)
            if n_review % 1000000 == 0:
                print(n_review, end=',')
            n_review += 1
            for _t, _ in d['review_sentences']:
                n_sentence += 1
                n_spoiler_sentence += _t
            n_spoiler_review += int(d['has_spoiler'])
            book_set.add(d['book_id'])
            user_set.add(d['user_id'])
    print('complete')
    print('done!')
    return n_review, n_sentence, n_spoiler_review, n_spoiler_sentence, len(book_set), len(user_set)

In [6]:
res = count_spoilers(os.path.join(DIR, 'goodreads_reviews_spoiler.json.gz'))
df_stats_spoiler = pd.DataFrame(res, columns=['count'], dtype=float, 
                               index=['# review', '# sentence', '# spoiler review', '# spoiler sentence',
                                      '# book', '# user'])
display(df_stats_spoiler)

counting file: ./goodreads_reviews_spoiler.json.gz
current line: 0,1000000,complete
done!

                          count
# review            1,378,033.0
# sentence         17,672,655.0
# spoiler review       89,627.0
# spoiler sentence    569,724.0
# book                 25,475.0
# user                 18,892.0

**Calculate basic statistics of review files for each genre:**

In [7]:
genre_list = ['children', 'comics_graphic', 'fantasy_paranormal', 'history_biography',
              'mystery_thriller_crime', 'poetry', 'romance', 'young_adult']

def count_all_genres(genre_list):
    res = []
    for g in genre_list:
        n_review, n_book, n_user = count_reviews(
            os.path.join(DIR_GENRE, 'goodreads_reviews_'+g+'.json.gz'))
        res.append([n_review, n_book, n_user])
    df_stats_by_genre = pd.DataFrame(res, dtype = float, 
                                     columns = ['# review', '# book', '# user'],
                                     index = genre_list)
    return df_stats_by_genre

In [8]:
df_stats_by_genre = count_all_genres(genre_list)
display(df_stats_by_genre)

counting file: ./genre/goodreads_reviews_children.json.gz
current line: 0,complete
done!
counting file: ./genre/goodreads_reviews_comics_graphic.json.gz
current line: 0,complete
done!
counting file: ./genre/goodreads_reviews_fantasy_paranormal.json.gz
current line: 0,1000000,2000000,3000000,complete
done!
counting file: ./genre/goodreads_reviews_history_biography.json.gz
current line: 0,1000000,2000000,complete
done!
counting file: ./genre/goodreads_reviews_mystery_thriller_crime.json.gz
current line: 0,1000000,complete
done!
counting file: ./genre/goodreads_reviews_poetry.json.gz
current line: 0,complete
done!
counting file: ./genre/goodreads_reviews_romance.json.gz
current line: 0,1000000,2000000,3000000,complete
done!
counting file: ./genre/goodreads_reviews_young_adult.json.gz
current line: 0,1000000,2000000,complete
done!

                          # review    # book    # user
children                 734,640.0 123,946.0  92,667.0
comics_graphic           542,338.0  89,311.0  59,347.0
fantasy_paranormal     3,424,641.0 258,212.0 256,088.0
history_biography      2,066,193.0 302,346.0 238,450.0
mystery_thriller_crime 1,849,236.0 218,987.0 203,655.0
poetry                   154,555.0  36,412.0  47,400.0
romance                3,565,378.0 334,957.0 198,141.0
young_adult            2,389,900.0  93,267.0 209,152.0